/* Daily quotes — themes: business, discipline, body, health, family, mindset */
window.QUOTES = [
  { q: "A focused fool can accomplish more than a distracted genius.", a: "Alex Hormozi", t: "mindset" },
  { q: "Make people an offer so good they would feel stupid saying no.", a: "Alex Hormozi", t: "business" },
  { q: "Those who pay the most, pay the most attention.", a: "Alex Hormozi", t: "business" },
  { q: "The longer you delay the ask, the bigger the ask you can make.", a: "Alex Hormozi", t: "business" },
  { q: "People don't have shorter attention spans, they have higher standards.", a: "Alex Hormozi", t: "business" },
  { q: "A person who pays with their time now is more likely to pay with their money later.", a: "Alex Hormozi", t: "business" },
  { q: "The more ways you measure, the more ways you can win.", a: "Alex Hormozi", t: "business" },
  { q: "The business that provides the most value wins. Period.", a: "Alex Hormozi", t: "business" },
  { q: "Price is what you charge. Value is what they get. The difference between price and value is goodwill.", a: "Alex Hormozi", t: "business" },
  { q: "Give away the secrets, sell the implementation.", a: "Alex Hormozi", t: "business" },
  { q: "Don't be clever, be clear.", a: "Alex Hormozi", t: "business" },
  { q: "The right action in the wrong amount still fails.", a: "Alex Hormozi", t: "business" },
  { q: "Hire experience, not potential.", a: "Alex Hormozi", t: "business" },
  { q: "If you're not learning from them in the interview, you've got the wrong person.", a: "Alex Hormozi", t: "business" },
  { q: "You get money from yeses. You get time from nos. You get nothing from maybes.", a: "Alex Hormozi", t: "business" },
  { q: "Volume negates luck.", a: "Alex Hormozi", t: "business" },
  { q: "How to stay poor: Start tomorrow.", a: "Alex Hormozi", t: "discipline" },
  { q: "How to stay poor: Find something that works. Stop doing it.", a: "Alex Hormozi", t: "business" },
  { q: "How to stay poor: Be easily distracted.", a: "Alex Hormozi", t: "discipline" },
  { q: "We are the result of our actions, not our aspirations.", a: "Alex Hormozi", t: "discipline" },
  { q: "Talented people do more reps than untalented people. The reps make them talented. The talent doesn't make them do reps.", a: "Alex Hormozi", t: "discipline" },
  { q: "To succeed you just need to do so many reps that it would be unreasonable for you to fail.", a: "Alex Hormozi", t: "discipline" },
  { q: "When in doubt, stack reps.", a: "Alex Hormozi", t: "discipline" },
  { q: "“Boring” is what most people call the work it takes to become the best.", a: "Alex Hormozi", t: "discipline" },
  { q: "Boring work leads to extraordinary outcomes.", a: "Alex Hormozi", t: "discipline" },
  { q: "The boring stuff is often what you need to do most.", a: "Alex Hormozi", t: "discipline" },
  { q: "Success comes down to doing the obvious thing for an uncommonly long period of time without convincing yourself you're smarter than you are.", a: "Alex Hormozi", t: "discipline" },
  { q: "The world belongs to those who can keep doing without seeing the result of their doing.", a: "Alex Hormozi", t: "discipline" },
  { q: "Most people stop too soon. We don't do enough.", a: "Alex Hormozi", t: "discipline" },
  { q: "Do more than they do, and you will have more than they have.", a: "Alex Hormozi", t: "discipline" },
  { q: "I promised myself I would never let effort be the reason anything didn't work for me.", a: "Alex Hormozi", t: "discipline" },
  { q: "Everything must be hard before it can be easy.", a: "Alex Hormozi", t: "mindset" },
  { q: "Be okay with sucking. It's new. This is how we learn.", a: "Alex Hormozi", t: "mindset" },
  { q: "Yeses give me opportunity. Nos give me feedback. Either way, I win.", a: "Alex Hormozi", t: "mindset" },
  { q: "A good night's sleep is both the reward and the price of a hard day's work.", a: "Alex Hormozi", t: "health" },
  { q: "Don't get bored. Be violent. Create your own enemies. Break your own records. Leave no doubt.", a: "Alex Hormozi", t: "body" },
  { q: "It's not what we do once in a while that shapes our lives. It's what we do consistently.", a: "Tony Robbins", t: "discipline" },
  { q: "The path to success is to take massive, determined action.", a: "Tony Robbins", t: "discipline" },
  { q: "You become what you do most of the time.", a: "Tony Robbins", t: "discipline" },
  { q: "Repetition is the mother of skill.", a: "Tony Robbins", t: "discipline" },
  { q: "Lots of people know what to do, but few people actually do what they know.", a: "Tony Robbins", t: "discipline" },
  { q: "If you do what you've always done, you'll get what you've always gotten.", a: "Tony Robbins", t: "mindset" },
  { q: "It is your decisions, and not your conditions, that determine your destiny.", a: "Tony Robbins", t: "mindset" },
  { q: "Focus on where you want to go, not on what you fear.", a: "Tony Robbins", t: "mindset" },
  { q: "Where focus goes, energy flows.", a: "Tony Robbins", t: "mindset" },
  { q: "You get what you tolerate.", a: "Tony Robbins", t: "mindset" },
  { q: "Success without fulfillment is failure.", a: "Tony Robbins", t: "mindset" },
  { q: "I can tell you the secret to happiness in one word: progress.", a: "Tony Robbins", t: "mindset" },
  { q: "Most people overestimate what they can accomplish in a year and underestimate what they can achieve in a decade.", a: "Tony Robbins", t: "mindset" },
  { q: "Every problem is a gift. Without problems we would not grow.", a: "Tony Robbins", t: "mindset" },
  { q: "Success is buried on the other side of rejection.", a: "Tony Robbins", t: "business" },
  { q: "The enemy of execution is complexity.", a: "Tony Robbins", t: "business" },
  { q: "The quality of your life is in direct proportion to the quality of your relationships.", a: "Tony Robbins", t: "family" },
  { q: "The secret to living is giving.", a: "Tony Robbins", t: "family" },
  { q: "A fit body, a calm mind, a house full of love. These things cannot be bought. They must be earned.", a: "Naval Ravikant", t: "health" },
  { q: "Knowledge workers function like athletes: train and sprint, then rest and reassess.", a: "Naval Ravikant", t: "health" },
  { q: "Desire is a contract that you make with yourself to be unhappy until you get what you want.", a: "Naval Ravikant", t: "mindset" },
  { q: "A rational person can find peace by cultivating indifference to things outside their control.", a: "Naval Ravikant", t: "mindset" },
  { q: "If it entertains you now but will bore you someday, it's a distraction. Keep looking.", a: "Naval Ravikant", t: "mindset" },
  { q: "You make your own luck if you stay at it long enough.", a: "Naval Ravikant", t: "discipline" },
  { q: "Wealth is assets that earn while you sleep.", a: "Naval Ravikant", t: "business" },
  { q: "Discipline equals freedom.", a: "Jocko Willink", t: "discipline" },
  { q: "If you don't think you are disciplined, it is because you haven't decided to be disciplined. Yet.", a: "Jocko Willink", t: "discipline" },
  { q: "The shortcut is a lie. The hack doesn't get you there.", a: "Jocko Willink", t: "discipline" },
  { q: "Comfort and luxury do not ambush you. You ambush yourself.", a: "Jocko Willink", t: "discipline" },
  { q: "It's not what you preach, it's what you tolerate.", a: "Jocko Willink", t: "business" },
  { q: "There are no bad teams, only bad leaders.", a: "Jocko Willink", t: "business" },
  { q: "Leaders must own everything in their world. There is no one else to blame.", a: "Jocko Willink", t: "business" },
  { q: "Relax. Look around. Make a call.", a: "Jocko Willink", t: "business" },
  { q: "Don't fight stress. Embrace it. Turn it on itself. Use it to make yourself sharper and more alert.", a: "Jocko Willink", t: "mindset" },
  { q: "I don't stop when I'm tired. I stop when I'm done.", a: "David Goggins", t: "body" },
  { q: "Doing things, even small things, that make you uncomfortable will help make you strong.", a: "David Goggins", t: "body" },
  { q: "We're either getting better or we're getting worse.", a: "David Goggins", t: "discipline" },
  { q: "Motivation changes exactly nobody.", a: "David Goggins", t: "discipline" },
  { q: "Denial is the ultimate comfort zone.", a: "David Goggins", t: "mindset" },
  { q: "No one is going to come help you. No one's coming to save you.", a: "David Goggins", t: "mindset" },
  { q: "You are in danger of living a life so comfortable and soft, that you will die without ever realizing your true potential.", a: "David Goggins", t: "mindset" },
  { q: "Either you run the day or the day runs you.", a: "Jim Rohn", t: "discipline" },
  { q: "Motivation is what gets you started. Habit is what keeps you going.", a: "Jim Rohn", t: "discipline" },
  { q: "Discipline is the bridge between goals and accomplishment.", a: "Jim Rohn", t: "discipline" },
  { q: "Success is nothing more than a few simple disciplines, practiced every day.", a: "Jim Rohn", t: "discipline" },
  { q: "We must all suffer one of two things: the pain of discipline or the pain of regret or disappointment.", a: "Jim Rohn", t: "discipline" },
  { q: "Success is doing ordinary things extraordinarily well.", a: "Jim Rohn", t: "discipline" },
  { q: "Don't wish it were easier. Wish you were better.", a: "Jim Rohn", t: "mindset" },
  { q: "Work harder on yourself than you do on your job.", a: "Jim Rohn", t: "mindset" },
  { q: "If your business depends on you, you don't own a business. You have a job.", a: "Dan Martell", t: "business" },
  { q: "Don't hire to grow your business. Hire to buy back your time.", a: "Dan Martell", t: "business" },
  { q: "80% done by someone else is 100% freaking awesome.", a: "Dan Martell", t: "business" },
  { q: "You aren't the best person to solve most problems anyway. Remember, your work is someone else's play.", a: "Dan Martell", t: "business" },
  { q: "A decision to not grow is a decision to slowly die.", a: "Dan Martell", t: "business" },
  { q: "Waste no more time arguing about what a good man should be. Be one.", a: "Marcus Aurelius", t: "discipline" },
  { q: "You have power over your mind, not outside events. Realize this, and you will find strength.", a: "Marcus Aurelius", t: "mindset" },
  { q: "If it is not right do not do it; if it is not true do not say it.", a: "Marcus Aurelius", t: "mindset" },
  { q: "You always own the option of having no opinion.", a: "Marcus Aurelius", t: "mindset" },
  { q: "We suffer more often in imagination than in reality.", a: "Seneca", t: "mindset" },
  { q: "Difficulties strengthen the mind, as labor does the body.", a: "Seneca", t: "body" },
  { q: "If a man knows not to which port he sails, no wind is favorable.", a: "Seneca", t: "mindset" },
  { q: "Associate with people who are likely to improve you.", a: "Seneca", t: "mindset" },
  { q: "Don't explain your philosophy. Embody it.", a: "Epictetus", t: "discipline" },
  { q: "First say to yourself what you would be; and then do what you have to do.", a: "Epictetus", t: "discipline" },
  { q: "No man is free who is not master of himself.", a: "Epictetus", t: "discipline" },
  { q: "If you want to improve, be content to be thought foolish and stupid.", a: "Epictetus", t: "mindset" },
  { q: "People are not disturbed by things, but by the views they take of them.", a: "Epictetus", t: "mindset" },
  { q: "You do not rise to the level of your goals. You fall to the level of your systems.", a: "James Clear", t: "discipline" },
  { q: "Every action you take is a vote for the type of person you wish to become.", a: "James Clear", t: "discipline" },
  { q: "Habits are the compound interest of self-improvement.", a: "James Clear", t: "discipline" },
  { q: "Professionals stick to the schedule; amateurs let life get in the way.", a: "James Clear", t: "discipline" },
  { q: "The only way to become excellent is to be endlessly fascinated by doing the same thing over and over.", a: "James Clear", t: "discipline" },
  { q: "You should be far more concerned with your current trajectory than with your current results.", a: "James Clear", t: "mindset" },
  { q: "Management is doing things right; leadership is doing the right things.", a: "Peter Drucker", t: "business" },
  { q: "There is nothing so useless as doing efficiently that which should not be done at all.", a: "Peter Drucker", t: "business" },
  { q: "Rank does not confer privilege or give power. It imposes responsibility.", a: "Peter Drucker", t: "business" },
  { q: "Unless commitment is made, there are only promises and hopes; but no plans.", a: "Peter Drucker", t: "business" },
  { q: "Results are obtained by exploiting opportunities, not by solving problems.", a: "Peter Drucker", t: "business" },
  { q: "Someone's sitting in the shade today because someone planted a tree a long time ago.", a: "Warren Buffett", t: "mindset" },
  { q: "It takes 20 years to build a reputation and five minutes to ruin it. If you think about that, you'll do things differently.", a: "Warren Buffett", t: "business" },
  { q: "The safest way to get what you want is to deserve what you want.", a: "Charlie Munger", t: "mindset" },
  { q: "Deliver to the world what you would buy if you were on the other end.", a: "Charlie Munger", t: "business" },
  { q: "I constantly see people rise in life who are not the smartest, sometimes not even the most diligent, but they are learning machines.", a: "Charlie Munger", t: "mindset" },
  { q: "There are no shortcuts. Everything is reps, reps, reps.", a: "Arnold Schwarzenegger", t: "body" },
  { q: "Strength does not come from winning. Your struggles develop your strengths.", a: "Arnold Schwarzenegger", t: "body" },
  { q: "You have 24 hours. Use them.", a: "Arnold Schwarzenegger", t: "discipline" },
  { q: "Never follow the crowd, go where it's empty.", a: "Arnold Schwarzenegger", t: "business" },
  { q: "Vision is the most important thing. Vision is purpose and meaning.", a: "Arnold Schwarzenegger", t: "mindset" },
  { q: "If you want to be a better player, you have to prepare, prepare, and prepare some more.", a: "Kobe Bryant", t: "discipline" },
  { q: "You have to work hard in the dark to shine in the light.", a: "Kobe Bryant", t: "discipline" },
  { q: "Rest at the end, not in the middle.", a: "Kobe Bryant", t: "discipline" },
  { q: "Everything negative, pressure, challenges, is all an opportunity for me to rise.", a: "Kobe Bryant", t: "mindset" },
  { q: "Good coaches tell you where the fish are, great coaches teach you how to find them.", a: "Kobe Bryant", t: "business" },
  { q: "Don't give up. Don't ever give up.", a: "Jim Valvano", t: "mindset" },
  { q: "If you laugh, you think and you cry, that's a full day. That's a heckuva day.", a: "Jim Valvano", t: "health" },
  { q: "Successful long-term relationships are created through small words, small gestures, and small acts.", a: "John Gottman", t: "family" },
  { q: "Working briefly on your marriage every day will do more for your health and longevity than working out at a health club.", a: "John Gottman", t: "family" },
  { q: "Friendship fuels the flames of romance because it offers the best protection against feeling adversarial toward your spouse.", a: "John Gottman", t: "family" },
  { q: "Love isn't a state of perfect caring. It is an active noun like struggle.", a: "Fred Rogers", t: "family" },
  { q: "The greatest gift you ever give is your honest self.", a: "Fred Rogers", t: "family" },
  { q: "Anyone who does anything to help a child in his life is a hero to me.", a: "Fred Rogers", t: "family" },
];
